In [3]:
import pandas as pd
import joblib

In [4]:
# load model.pkl
model = joblib.load("model.pkl")

# data baru
new_data = pd.DataFrame([{
    'BALANCE': 50.853021,
    'BALANCE_FREQUENCY': 1.0,
    'PURCHASES': 428.75,
    'ONEOFF_PURCHASES': 0.0,
    'INSTALLMENTS_PURCHASES': 428.75,
    'CASH_ADVANCE': 0.0,
    'PURCHASES_FREQUENCY': 1.0,
    'ONEOFF_PURCHASES_FREQUENCY': 0.0,
    'PURCHASES_INSTALLMENTS_FREQUENCY': 1.0,
    'CASH_ADVANCE_FREQUENCY': 0.0,
    'CASH_ADVANCE_TRX': 0.0,
    'PURCHASES_TRX': 18.0,
    'CREDIT_LIMIT': 8000.0,
    'PAYMENTS': 319.919021,
    'MINIMUM_PAYMENTS': 107.187821,
    'PRC_FULL_PAYMENT': 0.090909
},{
    'CUST_ID': 123,
    'BALANCE': 6593.820644,
    'BALANCE_FREQUENCY': 1.0,
    'PURCHASES': 388.66,
    'ONEOFF_PURCHASES': 388.66,
    'INSTALLMENTS_PURCHASES': 0.0,
    'CASH_ADVANCE': 4621.93458,
    'PURCHASES_FREQUENCY': 0.583333,
    'ONEOFF_PURCHASES_FREQUENCY': 0.583333,
    'PURCHASES_INSTALLMENTS_FREQUENCY': 0.0,
    'CASH_ADVANCE_FREQUENCY': 0.416667,
    'CASH_ADVANCE_TRX': 7.0,
    'PURCHASES_TRX': 7.0,
    'CREDIT_LIMIT': 7000.0,
    'PAYMENTS': 1624.583114,
    'MINIMUM_PAYMENTS': 2503.40234,
    'PRC_FULL_PAYMENT': 0.0
}])

# inference data baru
clustering = model.predict(new_data)

# hasil clustering
print("Hasil Clustering: ", clustering)

new_data["cluster"] = clustering
new_data.T

Hasil Clustering:  [1 2]

                                            0            1
BALANCE                             50.853021  6593.820644
BALANCE_FREQUENCY                    1.000000     1.000000
PURCHASES                          428.750000   388.660000
ONEOFF_PURCHASES                     0.000000   388.660000
INSTALLMENTS_PURCHASES             428.750000     0.000000
CASH_ADVANCE                         0.000000  4621.934580
PURCHASES_FREQUENCY                  1.000000     0.583333
ONEOFF_PURCHASES_FREQUENCY           0.000000     0.583333
PURCHASES_INSTALLMENTS_FREQUENCY     1.000000     0.000000
CASH_ADVANCE_FREQUENCY               0.000000     0.416667
CASH_ADVANCE_TRX                     0.000000     7.000000
PURCHASES_TRX                       18.000000     7.000000
CREDIT_LIMIT                      8000.000000  7000.000000
PAYMENTS                           319.919021  1624.583114
MINIMUM_PAYMENTS                   107.187821  2503.402340
PRC_FULL_PAYMENT                     0.090909     0.000000
CUST_ID                                   NaN   123.000000
cluster                              1.000000     2.000000